language: node_js

node_js:
  - node

cache:
  directories:
  - "$HOME/.npm"

before_install:
  - wget https://releases.leanapp.cn/leancloud/lean-cli/releases/download/v0.20.1/lean-linux-x64
  - mv lean-linux-x64 lean
  - chmod +x ./lean

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir:  dist
  keep_history: true
  on:
    branch: master
  fqdn: smc.wiki

after_deploy: 
  - npx vue-cli-service build --mode production --dest dist
  - ./lean login -u $LC_USER -p $LC_PASSWORD -r CN
  - ./lean switch SMC
  - ./lean deploy
  - ./lean publish