language: node_js

node_js:
  - node

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

before_cache:
  - brew cleanup

cache:
  directories:
  - "$HOME/.npm"

env:
  - VUE_APP_PUBLIC_PATH=/smc/

before_install:
  - wget https://releases.leanapp.cn/leancloud/lean-cli/releases/download/v0.20.1/lean-cli-x64.deb
  - sudo dpkg -i lean-cli-x64.deb

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir:  dist
  keep_history: true
  on:
    branch: master

after_deploy: 
  - npx vue-cli-service build --mode production --dest dist
  - lean login -u $LC_USER -p $LC_PASSWORD -r CN
  - lean switch SMC@DAY
  - lean deploy
  - lean switch SMC@NIGHT
  - lean deploy