language: node_js
node_js:
  - 11.6.0
cache:  npm

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir:  dist
  keep_history: true
  on:
    branch: master