os: osx

language: node_js

node_js:
  - node

before_cache:
  - brew cleanup

cache:
  directories:
  - "$HOME/.npm"
  - $HOME/Library/Caches/Homebrew

env:
- VUE_APP_PUBLIC_PATH=/smc/

install:
  - npm ci
  - brew install lean-cli

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir:  dist
  keep_history: true
  on:
    branch: master

after_deploy: 
  - lean login -u $LC_USER -p $LC_PASSWORD -r CN
  - lean switch SMC@DAY
  - lean deploy
  - lean switch SMC@NIGHT
  - lean deploy