language: node_js
node_js:
  - 11.6.0
cache:  npm

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip-clean up: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages